### ISSUE TITLE
If the ISO location is changed, updater doesn't offer to specifiy a new path and instead just launches primehack

### ISSUE THREAD

**Issue by Zhnigo** [SirMangler/PrimeHack-Updater#10]
Pretty much the title.

**Comment by SirMangler** [comment]
If the ISO path in the config is blank, it will prompt to ask again. If it is set to `NEVER`, it will not prompt and just launch Dolphin with the parameters supplied to the Updater (which is none unless you explicitly pass them with commandline or a shortcut). Otherwise it will attempt to launch Dolphin with the specified string.


> If the ISO location is changed

Changed to what in particular? I'm not sure I understand the issue.

**Comment by Zhnigo** [comment]
Sorry for not being clear enough - if the ISO is renamed or moved.

**Comment by SirMangler** [comment]
I see. You're right it doesn't check the validity of the iso path before running. It only checks the path when you're setting a new one. Nice catch, thanks.

Now resolved in:
https://github.com/SirMangler/PrimeHack-Updater/commit/3db83c5373349e146c67d35118df544beac86598
