### ISSUE TITLE
Updater can't see new compressed image types

### ISSUE THREAD

**Issue by Formedras** [SirMangler/PrimeHack-Updater#13]
The Open File Dialog for selecting a disc to autoload doesn't recognize WIA and RVZ extensions. (PrimeHack itself does, thankfully.)
Simple fix, just add those extensions to the dialog's mask.

**Comment by SirMangler** [comment]
Very good catch. I copied the list a long while ago and it's obviously been updated since.

Fixed in here: https://github.com/SirMangler/PrimeHack-Updater/commit/dcc60f75ac585a21f9cd0c41fc7aa87f5b7ee0fd

As for your personal case, you may be able to work around this issue by changing the extension to `ISO`. I believe Dolphin doesn't take too much notice of the file extension in the end. This isn't a great solution but will work in the mean time if you want the quicklaunch feature. I would like a new release to come out soon, I intend on improving this feature even more so.

**Comment by Formedras** [comment]
I did a slightly different workaround; after setting the autostart to a different image (in my case, a decompressed Trilogy ISO, though it should work with any valid ISO, even if it's not Metroid) in `updater.cfg`, I changed the `isopath` variable's path to my RVZ image.

Anyway, I'd also recommend additional filters in the dialog for each of the four formats that Dolphin can convert images to/from. (So one filter of just ISO, one of just GCZ, one of just WIA, one of just RVZ.) Absolutely not necessary, but it might help with folders filled with lots of images of mixed types.

**Comment by SirMangler** [comment]
>Anyway, I'd also recommend additional filters in the dialog for each of the four formats that Dolphin can convert images to/from. (So one filter of just ISO, one of just GCZ, one of just WIA, one of just RVZ.) Absolutely not necessary, but it might help with folders filled with lots of images of mixed types.

I appreciate the suggestion. Zero downside to having it, so I have added it here https://github.com/SirMangler/PrimeHack-Updater/commit/856ca718584b0a47ba108e4676ce7ef9d27225b0.

**Comment by Formedras** [comment]
Thanks for listening.

By the way, there's a typo in the GCZ filter. You accidentally put `GCZ Ffiles`, with an extra 'f' in there.

**Comment by SirMangler** [comment]
Whoops. Looks like I incorrectly amended that change. It's fixed now. I appreciate the feedback, hopefully these changes will be released soon. I'm awfully busy with university but generally I release updater versions with PrimeHack itself. Of course with any more ideas feel free to create a new issue.
