### ISSUE TITLE
UAC admin

### ISSUE THREAD

**Issue by AeliusSaionji** [SirMangler/PrimeHack-Updater#2]
Is it really necessary to request elevation for this?

**Comment by SirMangler** [comment]
The reason I set it to be UAC is in order to 1. Hopefully relax anti-viruses, and 2. To allow it to install in any directory. 

I don't need to do so many tactics to relax anti-viruses once enough of them have verified this is not at all a virus (through people excluding it). I can make it only request elevation when required and this is something I would like to do.

**Comment by AeliusSaionji** [comment]
I even tried the trick where you create a file `PrimeHack.Update.exe.manifest` with the permissions I wanted (and setting the access time of the binary to be newer), but for some reason this didn't work.

Making an unknown process have administrative elevation relaxes antivirus?! How does that work? Seems counter-intuitive haha.

To be honest, I think it would be better design to gracefully let the user know there is a permission error, rather than have a program that, as I understand it does nothing but download and extract a zip file, ask for `ADMINISTRATIVE POWER`.

**Comment by SirMangler** [comment]
A lot of anti-viruses (including Windows Defender) use machine learning and pattern scanning, the theory was by requesting administrator privileges it would appear as though this application was not attempting to hide anything. 

Many many installers request administrative permissions in the same way I have done. By doing this, when the anti-virus checks the application for code patterns, it would seem more similar to trusted applications. This isn't a clean cut solution, instead it's just trying to win more favour.

What would you suggest for informing users of a permissions error? The initial release announcement of the updater did include a disclaimer about false positives. I cannot present the user with a MessageBox once they run the application, without providing a separate executable, due to the fact the executable would have already been flagged long before it gets to that point.

My research has lead me to two conclusions on the matter:
1. Buy a commercial certificate (lots of money)
2. Wait until the Updater has been excluded enough times for the anti-viruses database to start trusting/becoming more familiar the application.

**Comment by AeliusSaionji** [comment]
> Wait until the Updater has been excluded

Excluded from antivirus, or smartscreen?
I also think that this use of admin to try and run-around antivirus is, frankly, incredibly irresponsible. Do not teach users to blindly elevate things, and do not so casually request elevation.

The "permission error" I refer to is about `2. To allow it to install in any directory.` If you don't have access to the folder, gracefully exit and let the user know why. If we've reached this point, we are beyond antivirus concerns.

**Comment by SirMangler** [comment]
Excluded from the anti-virus. If this happens enough times, this application will be less likely to be auto-flagged for being uncommon/not commonly ran. This is a genuinely used flag and it does trigger anti-viruses quite easily (for obvious reasons).

I don't see how it's irresponsible to request administrator, since this is an installer. Many users choose to install under Program Files, which is a UAC locked folder. Dolphin itself follows this same convention of requesting admin privileges, as with most installers I have used personally. 
This is standard to most Windows applications of this nature. 

With so many Windows updates, and Window's operating systems available, it can be irritating to cleanly detect when it requires elevated permissions in a decent manner. For example attempting to write, then failing due to lack of permissions could cause alarm to Windows Defender.

This updater is designed to make installation quick and easy. Not to interrupt users with an error which some may not understand how to solve, or more rightly, not understand why *they* have to solve it. This isn't "running around" the anti-virus. This is making it clear what the purpose is. This application isn't trying to hide that it is installing files, it is explicitly prompting the user for *permission* to fulfil it's task.

I agree that I would prefer it not request admin every time, this is irritating to even me and something I would like to alter. However it's worth remembering, I'm not a commercial company able to afford certificates, I'm not a known publisher. All I can do is try to convey the purpose of my app and attempt to be transparent with both the user and the anti-viruses they use. 

Interestingly, even Dolphin have received false positives in the past. It's very much a nuisance to genuine software providers and if you investigate online, you'll find many many people creating updaters and auto-installers encounter this problem.

**Comment by AeliusSaionji** [comment]
> It's very much a nuisance to genuine software

I'm aware of this, I don't doubt antivirus pegs you.

> I don't see how it's irresponsible to request administrator, since this is an installer.

I think we view this word and the functionality of this program through different perspectives. An installer provides a destination, creates shortcuts, potentially registers associations with the system. It installs. As far as I know, this project does none of that. This is what I would consider a self-updater for a portable-app.
When I saw your project and tried it, I thought, "this is a thing to simplify downloading from github, cool. I'll put it in AppData or something."

If you can make it not request admin for folders I already have write access to, I will be happy.

By way of conversation, I do have more to say on this subject:
The very concept of an installer elevating itself is pretty bonkers. The entire premise of the installer is a security nightmare (Linux package managers and UWP being the proper solution to software delivery). Yes, I know many installers operate in this way- that doesn't make it good or wise, and it just seems out of place for your project.

There's also a purpose to ProgramFiles beyond just "let's put this exe next to the other exes". If a program _needs_ to be elevated in the course of normal operation, then it should reside in a trusted location where potential attackers can't just swap out the binary. Do you want this to install to ProgramFiles? Fine, do it. Do you want this to be a portableapp thing? OK, do that. Presently, you've sort of hedged your bets and the app a weird suboptimal composite of both.

> the theory was by requesting administrator privileges it would appear as though this application was not attempting to hide anything.

I reread this a few times and I think I understand what you're saying... but you don't seem confident in the outcome, and I remain skeptical. If the only truly known solution is to exclude from antivirus, why not just tell users to do that on the download page?

**Comment by AeliusSaionji** [comment]
And I'm not here to yell at you for having done a thing in your free time differently than I would have.

Just my simple "huh why is it this way" seems to have spun off into a discussion of computer management values :)

**Comment by SirMangler** [comment]
> This is what I would consider a self-updater for a portable-app.

Agreed, that was the initial purpose of this, however it has been through stages in PrimeHack's development where it has been required to act as a migrator and utility. Because of this, I've adopted treating it as an installer as it started assuming more responsibility.

> If you can make it not request admin for folders I already have write access to, I will be happy.

I will be too. I will make this change on the next update. I was already considering it previously but I realise it really is just a nuisance for the user. This is one of a couple things I have tried to please the anti-virus overlords.

Admittedly I haven't spent as much time refining the updater as I would like too. Forgetting about trying to please AI, requesting admin before knowing if it needs to install anything is very silly.

> but you don't seem confident in the outcome, and I remain skeptical.  

I'm not confident with the outcome because I haven't received much feedback (not that I actively attempted to get it). 


I've been spending the majority of my effort into PrimeHack itself, one of the things I'm investigating could potentially make PrimeHack Updater obsolete. No promises or any announcements on it though, but it's pretty much the same process.

PS: I forgot that quotes exist. They're useful.

**Comment by SirMangler** [comment]
https://github.com/SirMangler/PrimeHack-Updater/releases/tag/1.5.5
